spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oldbookstore
    username: root
    password: jaimatadi

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect    
    
  mail:
    host: smtp.gmail.com
    port: 25
    username: kumarkundan380@gmail.com
    password: kunmuz@123
    
    properties:
      mail:
        debug: true
        transport:
          protocol: smtp
        smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
          starttls:
            enable: true  

jwt:
  secret: secret            
